abbrev_dict = {
    "cc": "coucou",
    "g": "j ai",
    "ns": "nous",
    "vs": "vous",
    "mtnt": "maintenant",
    "ptite": "petite",
    "ds": "dans",
    "tt": "tout",
    "tjr": "toujours",
    "bcp": "beaucoup",
    "pr": "pour",
    "nn": "non",
    "ca": "ça",
    "qqn": "quelqu'un",
    "tkt": "t inquiète",
    "pblm": "problème",
    "dsl": "désolé",
    "pk": "pourquoi",
    "pck": "parce que",
    "paske": "parce que",
    "ct": "c est",
    "trkl": "tranquille",
    "rdv": "rendez-vous",
    "ms": "mais",
    "tfk": "tu fais quoi",
    "avc": "avec",
    "acc": "accord",
    "ke": "que",
    "ki": "qui",
    "mwa": "moi",
    "stp": "s il te plait"

}